idf_component_register(
	SRCS 		"main.c"
			"ugui/ugui.c"
			"QRLib/qr_encode.c"
			"utils.c"
			"bsp.c"
			"net/ap.c"
			"net/http_server.c"
			"img_proc/img_proc.c"
			"lcd/yepd_if.c"
			"lcd/yepd.c"
			"lcd/YMS400600-040AAX-E6.c"
			"lcd/YMS800480-073AAX-E6.c"
			"lcd/YMS16001200-1330AAX-E6.c"
			"lcd/YMS25601440-3150AAX-E6.c"
			"pmic/IST9201.c"
			"arduino_wrapper.c"

        INCLUDE_DIRS 	"."
			"lcd"
			"net"
			"web"
			"img_proc"
			"ugui"
			"QRLib"
			"pmic"
	# EMBED_FILES 	"web/favicon.ico" "web/upload_script.html"
)
